server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://47.108.52.160:3306/cloud_order?useSSL=false
    username: root
    password: Mysql12345^
    driver-class-name: com.mysql.jdbc.Driver
#  application:
#    name: orderservice
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#        cluster-name: HZ

userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka/

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
develop:
  timefo: yyyy+MM-dd HH:mm:ss
feign:
  client:
    config:
      userservice:
        logger-level: BASIC
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数