server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://47.108.52.160:3306/cloud_user?useSSL=false
    username: root
    password: Mysql12345^
    driver-class-name: com.mysql.jdbc.Driver
#  application:
#    name: userservice
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#        cluster-name: HZ


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka/

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS